const String textHobbies = "Hobbies and qualities\n"
    "Inspiration can be found in very different ways. You can be inspired by anything, and often even by chance. Being observant (1) and open-minded about the world around you will help you do that. However, should you ever have a creative dry spell; we have a few suggestions that might help you find inspiration again.\n"
    "The word \"inspiration\" comes from Latin and it means \"to breathe into\". The terms are colloquially used to express the process of being mentally stimulated to do or feel something, especially to do something creative. Finding inspiration can be a challenge for many, especially when work and a strict routine might exhaust your energies. So if you're looking for inspiration, why don't you:\n"
    "Try to step out of your comfort zone\n"
    "Of course, that's easier said than done. In your cozy comfort zone, everything is uncomplicated and risk-free. But what if the best inspiration is waiting for you outside your comfort zone? You don't have to go all out and take a trip around the world or anything extreme like that. Even small changes can make a big difference. Eat at a new restaurant, watch a movie alone, or talk to a stranger on the street. Just doing things you've never done before because you're afraid of them will charge your energy batteries and make you see what is around you in a different way. One step further can also be spending some time abroad: this is the best and most effective way to leave your comfort zone behind!\n"
    "Take time for yourself\n"
    "When was the last time you were completely alone with your thoughts? Sometimes life can get overwhelming, and a little peace and quiet can take you a long way. Turn off your smartphone, TV and laptop, close the door or go for a walk and take a moment just for yourself. Let your thoughts run free and don't try to come up with the perfect idea right off the bat. The best ideas come spontaneously, so try not to think too hard. Think of it more as a creative break and let your quiet surroundings positively influence you.\n"
    "Learn something new\n"
    "Learning something new can really stimulate your brain. The challenge of facing something unfamiliar, as well as the seeing yourself improve day by day, will renew your energies and really give you a boost. Think about what you've always wanted to do. Playing the piano has always fascinated you? You think French is a beautiful language and you wish you could understand it? Think now about what is stopping you - and too little time or too much effort are not good excuses! So book that language course, buy or borrow that musical instrument, or join the gym, you will not be disappointed!\n"
    "Find the perfect place\n"
    "Inspiration is often associated with specific places. It is not always easy to find your inspiration at your desk or in your too-familiar apartment. By exploring new places you will definitely have a new perspective on your life, needs, and desires. Even travelling a couple kilometers away from your front door or office can be enough. If you have a little more time and resources, a vacation is guaranteed (2) to help you expand your sources of inspiration.\n"
    "Go on vacation\n"
    "On vacation everything is usually new to you - new surroundings, different people, and a foreign culture. Sometimes taking time from your everyday life and discovering something new is enough to boost your energy and your inspiration. Anything from big cities with stimulating culture to quiet nature getaways is a trip worth taking. Going on a language trip is an optimal solution combining vacation and learning, two great sources of inspiration that will gift you new ideas, new insights and, in renewed inspiration.\n"
    "Brainstorm with others\n"
    "It's always good when you can talk to others about your ideas and future plans. If you are lucky, you already have someone in your life who is very similar to you, and whom you can exchange ideas with. But it can also be someone new in your life. Often, fresh thoughts and diverse (3) perspectives can help you come up with new ideas.\n"
    "Meet new people\n"
    "Some people find it easier and some harder to strike up a conversation with new people. If you are a very sociable person, try to approach a stranger that sparks your interest and chat about your interests. However, if the idea of actively going to someone you don't know and starting a conversation terrifies you, then why not join a group of like-minded people? Travel, sport, or culture groups are a great way to meet people with similar interests. Meeting new people often brings a new perspective that inspires you.\n"
    "Take your time\n"
    "One fundamental thing in your search for inspiration is time and patience. Don't immediately throw away the piece of paper with just wrote because you're not happy with the result. Time and space away from it will give you a new perspective, and will allow you to see the value of it. It can take a little longer than anticipated (4) to be satisfied with the result of what you've done. Often you have to rework something and look for new inspiration again before it gets to where you want it to be. Inspiration is a process that takes time. Sometimes you might get a sudden inspiration followed by weeks of nothing. Don't worry; it will come to you again. The important thing is to start simple and not be afraid to make a mistake.\n"
    "Inspire yourself\n"
    "If you are at a loss for ideas in one area, a creative phase in another can be extremely helpful. Painting, sowing, or writing a poem can clear your head, and allow you to face your actual problem with a freer mind.\n"
    "Don't overthink\n"
    "Inspiration usually comes spontaneously (5). How, when and where inspiration will strike can't really be planned in advance. If you try to force yourself to be inspired it will usually produce the opposite result, leaving you frustrated and without ideas. Although it might sound rather cliche, inspiration does happen spontaneously and come from within you. So try to focus more on yourself instead of constantly focusing on finding inspiration - and the inspiration will come.\n";

const String textRunning =
    "Exercise and sport.  Running is a sport practiced by people everywhere around the world. Some people run casually for exercise. Some people train as professional runners, running in races and competing for fast times. For the Tarahumara people, running is an especially important part of their lives and community.\n"
    "The Tarahumara, or Rarámuri, are an indigenous (1) people from Chihuahua, Mexico. They are one of the largest indigenous communities in North America. The area that the Tarahumara live in is known as the Sierra Madre. The Tarahumara are famous around the world for their incredible skill as runners. Traditionally, the Tarahumara have always valued running skills very highly. This is because of their hunting traditions. The Tarahumara often participated in a form of hunting called “persistence hunting.” In this mode of hunting, hunters chase animals down on foot. Instead of shooting an animal with a bow and arrow, the Tarahumara hunters would chase it until it died of exhaustion. This technique requires an incredible amount of endurance (2) and speed.\n"
    "Outside of its importance in hunting traditions, running is also very important as a sport and spiritual act for the Tarahumara. Running events are community-oriented. Both men and women can run in these hours- or day-long competitions. There are different forms of footraces that the Tarahumara compete in. One kind of race is called the rarajípare. This race involves (3) two teams, each with 12 men. Each man on a team has to run the same distance. The men kick small wooden balls back and forth to their teammates as they run. As the runners compete, they have to cross streams and climb hills. The whole time, they must keep passing the ball to their teammates. The first team to run a set number of miles wins the race. These races can take hours or even days, depending on how many miles long they are. Some races are as short as 15 miles, while some are as long as 90 miles!\n"
    "The women’s version of this race is called ariwete. Instead of kicking a ball back and forth, women runners use hoops and sticks in their race. During the ariwete, runners carry sticks with hooks at the end. They use these sticks to hit hoops. The hoops are made with wood and cloth. This hoop is hit from runner to runner.\n"
    "As the competitors run in these races, community members will sometimes run alongside them, shouting encouragement. A common phrase that they shout is “Iwériga, iwériga!” This word means “breath” and also “soul” in the Tarahumara language. Iwériga shows how connected the Tarahumara’s spiritual (4) beliefs are with their running practices. For the Tarahumara, breathing is a spiritual practice. The breath of life is an important part of the Tarahumara creation myth. For the Tarahumara, showing strength by running a long distance and controlling the breath is also a spiritual act. The rarajípare is sometimes thought of as a way of praying.\n"
    "Tarahumara runners have become known around the world for their running skills. Their traditions of persistence (5) hunting and footraces have fostered many powerful runners within this indigenous group.\n";

const String textCharity = """
      "Charities and conflict\n"
      "Meet three young people who have cooked up cool culinary careers!\n"
      "Flynn McGarry, Haile Thomas, and Eliana de Las Casas are changing the nation’s ideas about food—and about the people who prepare it. All three are successful young food professionals who started their culinary (1) careers when they were kids.\n"
      "These three young people began as kid cooks, but today all three have earned the title of “chef.” The difference between a cook and a chef is like the difference between a jogger and an Olympic runner. High-level chefs are expected to produce highly memorable meals, know numerous cooking techniques, and follow special culinary rules. So how did these talented young chefs make the grade?\n"
      "From Takeout to Fine Dining\n"
      "The first sign of Flynn McGarry’s future in food may have been when, at age three, he dressed up for Halloween as Emeril, the New Orleans cuisine personality. When he was 10, Flynn’s parents broke up, and takeout food became his nightly dinner. The grade-school student began watching internet videos to learn how to make home-cooked meals.\n"
      "Soon, McGarry was taking cooking classes and exploring the restaurant business. By the time he turned 15, he had opened a successful “supper club” in his home, charging (2) his guests \$160 a plate! In 2018, at age 19, Flynn achieved one of his dreams by opening his own “fine dining restaurant,” Gem, in New York City. “I hope I inspire young people to see that there are different routes to take in cooking,” he told Fine Dining Lovers.\n"
      "Healthier Meals to Help Her Dad\n"
      "Haile Thomas was just 11 years old when she was chosen to bring her cooking skills to the White House and meet First Lady Michelle Obama. Thomas’s dish of quinoa, black bean, and corn salad was one of the winners of Obama’s “Healthy Lunchtime Challenge.”\n"
      "Haile began her cooking adventures in response to her father’s unhealthy diet. His diabetes was threatening to get worse, but she had a plan: Haile upgraded her family meals with healthy choices, and her father’s condition improved dramatically. Soon, Haile had her own YouTube show called “Kids Can Cook.” She was nine years old!\n"
      "When she was 12, Haile founded a nonprofit organization, HAPPY, to spread her messages of good food and healthy lifestyle. She’s also written a cookbook and appeared on numerous TV cooking shows.\n"
      "‘Chopped’ Champ Wins \$25,000\n"
      "Eliana de Las Casas came to her cooking career with zest (3) when she created “Spice It Up!” —low-salt seasonings to flavor meat, fish, and vegetables. In 2016, she was a contestant on the Food Network’s Chopped Teen Grand Champion show and won, beating out (4) 15 other teenage chefs and taking home the top prize of \$25,000. De Las Casas, who has been called a “pint-sized culinary phenomenon” has family roots in Louisiana, Cuba, Honduras, and the Philippines. Her accomplishments (5) include radio shows—"Cool Kids Cook” and “Let’s Get Cooking”—and four cookbooks.\n"
      "Chef Eliana loves the feeling of power that comes from combining ingredients and making something delicious out of them. And, she adds, the great thing about becoming a good cook is that it doesn’t require years of training: “You can do it now.”\n" """;

const String textTradition = "Tradition and language \n"
    "“Aren’t we there yet?” Omari asked, for the hundredth time.\n"
    "The 14-year-old felt as if he had been sitting in the backseat of his parents’ car for years. They’d been on the road since yesterday, driving on drab, dull ugly highways as they headed toward his first big family reunion in Atlanta, Georgia.\n"
    "Omari’s parents assured him that the trip would be fun. “You’ll get to meet lots of cousins and learn about your culture,” his mom promised. “It will be exciting!”\n"
    "Uh huh. Excitement wasn’t what Omari was feeling at the moment. “Bored and nervous at the same time” was more like it. He wished he could have stayed home in New York and read books, played video games, and checked in with his school buds. The truth was, Omari was small for his age and kind of quiet, and he didn’t always feel comfortable meeting new people. He’d rather get lost in stories and games and books, where situations and characters were familiar. Going to a family reunion? That sounded more like torture than like fun.\n"
    "Weary, Omari sank back (1) into his seat. He pulled out a video game, but he’d already played for hours and his console was dead. Then, remembering that he’d brought his favorite book of Langston Hughes poems, he flipped it open and began to read. The rhythm of the road got to him, however, and he soon fell asleep.\n"
    "An hour later, he opened his big brown eyes and saw that they were parked near a huge sign that read, “WASHINGTON FAMILY REUNION.” Dozens of Black people of all ages were gathered on the lawn behind the sign.\n"
    "“Are all of these people family?” Omari wondered out loud. His dad moved his slender arm across the whole scene and happily replied, “Pretty much!”\n"
    "Omari jumped out of the car and was immediately bombarded by family members. An older woman with wild grey hair—she looked like she had a squirrel on her head—came right up to him.\n"
    "“Hey there, are you Dianne and Billy’s son?” she asked, with a big smile, adding, “Look how big you’ve gotten!”\n"
    "The squirrel-haired woman hugged him and began to pinch his cheeks. Omari grabbed his face to make sure it was all still there. I’m too old for this, he thought. Soon after, his parents introduced her as his Aunt Mabel. Behind them was a big white farmhouse where Mabel lived, and coming out of it was a tall boy around his age, walking with a heaping plate of food.\n"
    "Omari’s stomach growled so loudly that he worried everyone could hear it.\n"
    "“Hey, cuz! I’m Kevon,” said the boy.\n"
    "“What’s good? I’m Omari,” he replied.\n"
    "“What’s good? Oh man, you must be from New York!”\n"
    "Omari laughed as the two dapped each other up.\n"
    "“Kevon, take your cousin inside for some food, you hear?” Aunt Mabel said to her son.\n"
    "“Yes, mama. His stomach is growling’ like an upset bear!” Omari let out an embarrassed laugh and followed Kevon inside.\n"
    "On a huge kitchen table, Omari saw baked ham, collard greens, fried chicken, black-eyed peas, candied yams, and lots more. Soul food! His eyes grew wide. He had eaten soul food in New York, but it never smelled or looked as good as this.\n"
    "“Our family has been passing down (2) recipes for generations,” Kevon told him, “and some of the best are on this table.” Omari piled his plate high with food, and then he and Kevon took a seat in the lively, people-filled living room, where he met more cousins, more aunties, more uncles, more cheek-pinchers.\n"
    "I guess Kevon doesn’t think he’s too old for this, Omari thought as he watched Kevon joke and laugh and accept his family’s love.\n"
    "The two of them moved through the crowd, sampling dish after dish and savoring each morsel.\n"
    "Hey, Omari thought, maybe this day will turn out OK, after all.\n"
    "At that moment, the sweet sound of someone singing filtered into the dining room. “I know who that is!” Kevon exclaimed, and led Omari to a room where they found another cousin—a teenager with a bright smile named Camille. She was doing a lively version of This Little Light of Mine, and Kevon immediately joined in, singing harmony. Omari felt a little self-conscious (3) about singing, so he clapped along instead.\n"
    "When Camille was done, Omari told her, “You have a beautiful voice! I never heard gospel sung like that before.”\n"
    "“Thanks,” Camille said, “that’s Chicago-style gospel, from the place where gospel was born!”\n"
    "“Really?” Kevon butted in. “I always thought gospel music came from here—the South.”\n"
    "“Well, it started in the South with Negro spirituals,” Camille retorted, “but the Black gospel music you hear today has its roots in my hometown, Chicago.”\n"
    "Omari, still feeling a little uncomfortable, shyly asked Camille if she might sing one of his favorite gospel songs, “Jesus Loves Me.”\n"
    "“Only if you sing it with me,” Camille replied, her bright smile teasing him. Pushing himself a little, Omari sang along as she got started.\n"
    "“Go ‘head, Omari, you can sang!” Camille said. Omari’s cheeks grew red as he began belting out notes.\n"
    "All of a sudden, the huge sound of a bass playing outside interrupted their song. When the three cousins went outdoors to investigate, they discovered a girl, a little younger than they were, with cool multicolored barrettes in her hair. She was surrounded by family and moving with awesome energy. Folks were shouting, “Go, Deandra, go!” as she grooved (4). It was hip hop…with a twist!\n"
    "When the dancing stopped, Omari, Kevon, and Camille introduced themselves and found out that Deandra was another cousin.\n"
    "“Hey, what is that dance called?” Camille queried.\n"
    "“Turfing,” Deandra responded cheerily. “It’s really big in Oakland.”\n"
    "“You mean California?” Omari said, surprised. He had family on the west coast, too?\n"
    "“Yup! I’ve been turfing since before I could speak! It’s cool! Come on, all of you should try it!”\n"
    "The music started up again and Deandra pulled Omari in. Soon all three cousins were following her lead—gliding, flexing, and contorting like she did… well, as best they could.\n"
    "When the music stopped, the four walked over to a little pond on the north side of the farmhouse. The sun was moving low in the sky, sending light reflecting across the surface of the water.\n"
    "“Okay, Omari,” Kevon announced as they sat by the pond, “we’ve all shared stuff from where we’re from. Now it’s your turn to show us some New York.”\n"
    "Omari grew quiet, wondering what he could possibly share. Then his face lit up. “Here’s some New York poetry,” he said, pulling out that favorite book of his. He opened to an inside page and read out loud two short poems by Langston Hughes.\n"
    "“These aren’t just poems, they’re part of a movement,” Omari added. “It was called the Harlem Renaissance, and it was dope (5)! Some very cool Black art and culture came out of that time. My faves are the poets, and there’s not just Langston Hughes, there’s also Gwendolyn Brooks, Countee Cullen, and…”\n"
    "Kevon guffawed and pointed to Omari, exclaiming, “Wow, because, that’s the most you’ve talked all day!”\n"
    "Then Camille said, “I’ll bet you write poetry, too. Do you, Omari?”\n"
    "“I try,” he replied. And with that, Omari stood up straight and walked to a spot in front of his three newfound relatives, stood quietly for a moment, then began reciting:\n"
    "Today I met three cousins\n"
    "They are a lot of fun!\n"
    "I learned so much from them today\n"
    "And I’ll miss them when I’m gone.\n"
    "Omari bowed, the three cousins clapped and laughed… and the four of them kept on laughing till long after the sun went down.\n";

const String textMusic =
    """Ricky sits at the kitchen table, imitating the drum beat of his favorite song as he finishes his math homework. His pencil moves in time to the percussive (1) rhythms booming from his ear buds.
Grandma Johnson comes into the kitchen just as Ricky is stuffing his math notebook back into his backpack.
“I don’t know how you get anything done listening to that hippity hoppity noise!” she exclaims.
Ricky takes out his ear buds and fights hard not to roll his eyes. He knows Grandma Johnson is half-teasing. But the hip-hop rhythms soothe his mind and quiet his thoughts, allowing his brain to focus on the page.
“Guess what, Grandma?” says Ricky, smugly. “I’m finished with my homework.”
Without his earbuds, Ricky can now hear the music playing in the background—a song by Diana Ross and the Supremes. Pushing aside his annoyance, he takes his grandmother’s hand and gives her a little twirl, the way Grandpa Johnson used to do before he passed away two years ago. “Someday, we’ll be togeh-eh-eh-ther,” Ricky sings along to the chorus.
Ricky has always felt close to his grandma. And now that his high school is near his grandmother’s Brooklyn home, he goes to Grandma’s every day to eat dinner and do his homework before heading home to Harlem. Ricky knows his presence helps ease his grandmother’s loneliness, and he loves spending time with her. But… he just wishes she would stop dismissing his favorite music as noise.
***
“I have a surprise for you,” Grandma tells Ricky at dinner that evening.
“Oh, word?” He did get a 98 on his last geometry test. Maybe she’s finally bought those sneakers he’s been hinting about?
Grandma holds up her phone and points to the screen. “I got us tickets to see Stevie Wonder!” she says delightedly, her eyes twinkling (2) like a teenager’s.
Ricky tries not to show his disappointment. “Oh, great. Thank you, Grandma.”
As they finish dinner, Grandma Johnson pulls out her old photo albums. She points to a picture of herself at fifteen, wearing bell bottom jeans and a cropped shirt under a fringed suede vest, her Afro a glorious dark halo. “On this day,” she tells Ricky, “I snuck out (3) with two of my cousins and went to a music festival uptown where Stevie was playing.”
She flips forward in the album, pointing to pictures and telling stories Ricky has heard a million times. She holds up one of Ricky’s favorite pictures of his grandparents: both with sky-high Afros, Grandpa in a dashiki and bell-bottoms, Grandma in a minidress.
“This was 1972. We were on our way to a Stevie Wonder concert,” Grandma Johnson laughs. “And now I get to continue the tradition—with you!”
Ricky smiles for his grandmother’s sake. He knows she has a huge collection of 1960s and 70s vinyl records. When Ricky was little, he would cringe when Grandma pulled out a record from her vast library and played it for him on her ancient turntable. Still, thanks to her efforts, he is familiar with the music of Aretha Franklin, Curtis Mayfield, Marvin Gaye, and other artists of her era—and yes, her favorite, Stevie Wonder, too.
“This is not just music,” Grandma always tells him. “This is History, culture.” But Ricky feels the same way about his favorite music—hip hop.
Ricky and his dad have been to hip hop concerts, shows full of electric energy and excitement. But a Stevie Wonder concert today—an old guy on stage, playing a keyboard and singing? No dancers? No special effects? How boring!
***
When the day of the concert arrives, Ricky still hasn’t told any of his friends where he is going. He figures that—if they even have a clue who Stevie Wonder is—none of them would be impressed.
 
Dutch National Archives
Stevie Wonder in 1967
Ricky holds his grandmother’s hand as they exit the subway station and follow the crowd to Madison Square Garden. Most of the people in the crowd are old-ish. Make that old, he thinks, seeing the gray hair of the people in front of him… Make that ancient.
As Ricky and Grandma take their seats, he hears people talking about past concerts, about Stevie’s activism and his messages of love and unity. When the lights dim, Ricky squeezes Grandma’s hand.
One by one, band members come on stage and take their places. Finally, a man walks out with Stevie Wonder on his arm as the crowd roars. He leads the artist to his seat behind the keyboard. Stevie fiddles with the keys a bit, and then… Madison Square Garden is awash in sound. In the dim (4) light, Ricky sees his grandmother as the young woman from her photographs, grooving to the music.
Hearing and seeing these songs performed live is different from listening to the old recordings. Each member of the band is focused on his or her own performance, but the instruments blend together seamlessly (5) to produce beautiful, harmonious sounds. Soon, he is clapping and dancing in his seat. He closes his eyes and lets the music wash over him, feeling the vibrations of the bass and the beat of the drum deep in his soul. Steve Wonder’s voice is strong and sure, sounding even better than Grandma’s records. And when Stevie puts the harmonica to his mouth, Ricky screams for joy as loud as anyone in the crowd.
When the bass line for “Do I Do” drops, Ricky makes a startling discovery. He doesn’t only know this song from Grandma’s albums. He knows it as one of the early 2000s hip hop tunes his Dad loves so much -- a song by the rapper Ja Rule. And when the opening notes for “Superwoman (Where Were You When I Needed You)” play, in his head, Ricky also hears a song from one of his own favorite artists – Frank Ocean’s “Sweet Life.” He bops his head in time to the beat, feeling an even deeper connection to this music.
When Stevie and the band leave the stage for a short break, Ricky gives his grandma a big hug.
“So, you’re having a good time?” Grandma Johnson says, laughing. “The way you screamed when he played the harmonica!”
Ricky laughs, feeling a little embarrassed. “Sorry Grandma. I guess I got a little carried away. But,” Ricky says, his eyes big with awe, “how can he sound even better than his records?” He pauses. “And you know the best part? Of course I know all of these songs from you playing them for me over the years. But I just realized that I know some of these songs from my own music, too. Well, from my music and Dad’s music.”
“What? That hippity-hop?” “Yeah, Grandma! I recognize some of the songs - or parts of them, anyway -- from hip hop!” “How’s that?”
“It’s called sampling. A producer will take a little part of this song, a little part of that song, and when they put it all together, you have something new that borrows from and builds on the music of the past.”
The house lights begin to dim again. “Tell me more after the concert,” Grandma Johnson says, just as the stage lights up.
 """;
const String textTravel =
    """It is hard to argue that the actual contribution to development amounts to a great deal directly. Whilst volunteer tourists can get involved in building homes or school, they have usually paid a significant fee for the opportunity to be involved in this work: money that, if donated to a local community directly, could potentially pay for a greater amount of labour than the individual volunteer could ever hope to provide. This is especially so in the case of gap years, in which the level of technical skill or professional experience required of volunteers is negligible (1). Hence, it is unsurprising that many academic studies allude to the moral issue of whether gap year volunteering is principally motivated by altruism- a desire to benefit the society visited- or whether young people aim to generate “cultural capital” which benefits them in their careers.
However, the projects may play a role in developing people who will, in the course of their careers and lives, act ethically in favour of those less well-off. 
Volunteering may lead to greater international understanding; enhanced ability to solve conflicts; widespread and democratic participation in global affairs through global civic society organizations; and growth of international social networks among ordinary people. In this scenario, the whole is greater than the sum of its parts, an outcome where benefits accrue (2) to volunteers and host communities, and contribute to the global greater good. However, if volunteering is largely limited to individuals of means from wealthier areas of the world, it may give these privileged volunteers an international perspective, and a career boost, but it will do little for people and communities who currently lack access to international voluntary work. Those who volunteer will contribute to reap its benefits, using host organizations and host communities as a rung on the ladder of personal advancement. 
As it worst, international volunteering can be imperialist, paternalistic charity, volunteer tourism, or a self-serving quest for career and personal development on the part of well-off Westerners. At its best, international volunteering brings benefits (and costs) to individual volunteers and the organizations within which they work, at the same time as providing the space for an exchange of technical skills, knowledge, and cross-cultural experience in developing communities. Most significantly, volunteering can raise awareness of, and a lifelong commitment to combating, existing unequal power relations and deep- seated (3) causes of poverty, injustice, and unsustainable development. 
Volunteer tourism seems to fit well with the growth of life strategies to help others. Such limited strategies, aimed at a humble “making difference”, can appear positive and attractive in an anti-political climate. The personal element appears positive- it bypasses big government and eschews big business. Yet it also bypasses (4) the democratic imperative of representative government and reduces development to individual acts off charity, most often ones that seek to work around rather than transform the situations of poor, rural societies. Cynicism at the act of volunteering is certainly misplaced. The act of volunteer tourism may involve only simple, commendable charity. However, where volunteer tourism is talked up as sustainable development and the marketing of the gap-year companies merges into development thinking, this is symptomatic of a degradation of the discourse of development. The politics of volunteer tourism represents a retreat (5) from a social understanding of global inequalities and the poverty lived by so many in the developing word. 
 """;
const String textScience = """Need a hand? It's not a problem with a 3D printer.
Coming out of today’s 3D printers: Bionic body parts! Vegan meals! Homes to live in!
A quiet but major revolution is sweeping across the world: 3D printers are transforming the way people build, make, and acquire things.
Just as its name implies, a 3D printer is able to produce a physical object, usually using a computer-aided design program or a 3D scanner. The printer recreates an image as a nozzle (1) squirts out very thin layers of a material like plastic or metal, one layer directly on top of another. Over a period of time, the layers build up, harden, and become a three-dimensional, physical item.
Today, people are using this technology to print a remarkable array of things—something unthinkable just a few years ago.
Print Out a House?
Can you imagine building a house in one day? A collaboration between a nonprofit organization and construction company in Texas is leading a revolution in homebuilding. It uses a gigantic 3D printer to build small homes by squirting layers of concrete to build floors and walls. Once the house has been “printed” on the 33-foot-long 3D printer, construction workers install windows, doors, and plumbing. These homes aren’t flimsy (2): they are designed to withstand hurricanes and earthquakes. The group has built its first neighborhood of 3D printed houses in southern Mexico, which will cost their new owners less than \$20 a month for seven years.
In another startling example of how far this technology has come, 3D printers have been used to create medical devices like hearing aids, surgical implants, or even replacement limbs. A Florida company has found a way to produce bionic arms for children that can be customized (3) with superhero designs. These replacement arms use sensors to generate arm and hand movements that enable children to perform everyday tasks like getting dressed. Even better, the arms can be adapted as a child grows bigger.
3D printers can even be used to create food. Companies are exploring the use of plant-based materials to create vegan steaks and burgers. When a customer places an order, a robot prints a layer of ingredients, cooks it, prints another layer, cooks it, and so on, until a burger is fully assembled and ready to serve—all in less than six minutes.
For a sweeter treat, how about custom-decorated desserts? A bakery in Ohio takes orders for 3D printed cakes and cookies. A blank cake is inserted (4) into a machine that prints the icing and frosting into a custom design on the surface. The process takes less than two hours, making a printed cake the perfect solution for a last-minute celebration.
Toys, Jewelry, Furniture … and More
These examples highlight some ways that 3D printing technology is making it cheaper to produce objects that are usually very expensive. Even better: the technology itself is becoming less expensive too, and is now used more often in different fields.
Architects are using 3D printers to create small-scale models of homes or furniture that make it easier to imagine what a finished building might look like. Jewelry designers can use 3D printers to create custom designs out of resin or metal. There are even 3D printers designed for kids to use at school or home to create plastic toys.
The possibilities for 3D printing are practically endless! With this technology gaining (5) popularity and transforming industries, one thing seems clear: the revolution will be printed.
 """;
